### ISSUE TITLE
fSharp not compatible with homebrew

### ISSUE THREAD

**Issue by AndyStewart** [fsharp/fsharp#451] opened 2015-07-16 21:55 UTC
Don asked me to post this here, but it may actually be an issue with homebrew.

Reproduction steps
===============

1. On a mac, install mono and fsharp using brew.
2. Clone project scaffold(https://github.com/fsprojects/ProjectScaffold/),
3. Run ./build.sh to create the project
4. Then run ./build.sh again to compile the project.

You'll now get an similar to below:

 error : Target named 'Rebuild' not found in the project.

It's got something to do with it not resolving the fsharp.targets, the fix for me was to uninstall mono via tap and then reinstall mono from xamarin studio.

**Comment by sgtz** [comment] 2015-07-27 03:07
I reproduced the error on OSX.  Note: the Rebuild issue comes up on step 3 for me.  I'll try to investigate further.

**Comment by sgtz** [comment] 2015-07-27 04:11
possibly related to line 132 of build.fsx script ---   !! solutionFile |> MSBuildRelease "" "Rebuild"

Was there ever a rebuild tag in the .sln?

**Comment by dcohenp** [comment] 2015-07-27 06:20
I think this is the issue I mentioned in a comment in fsprojects/ProjectScaffold#189. The problem does indeed seem to be caused by the missing Microsoft.FSharp.Targets, but it doesn't actually have to do with the ProjectScaffold-supplied code.

Rather, it looks like the Homebrew-supplied keg is breaking the directory structure which everything else relies on. Consider:

```
dcohenp@eizbook:~$ uname -a  # Yosemite
Darwin eizbook.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
dcohenp@eizbook:~$ brew install mono
==> Downloading https://homebrew.bintray.com/bottles/mono-4.0.2.5.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/mono-4.0.2.5.yosemite.bottle.1.tar.gz
==> Pouring mono-4.0.2.5.yosemite.bottle.1.tar.gz
==> Caveats
To use the assemblies from other formulae you need to set:
  export MONO_GAC_PREFIX="/usr/local"
==> Summary
🍺  /usr/local/Cellar/mono/4.0.2.5: 1006 files, 178M
dcohenp@eizbook:~$ ls -l /usr/local/lib/mono
lrwxr-xr-x  1 dcohenp  admin  31 Jul 27 02:52 /usr/local/lib/mono@ -> ../Cellar/mono/4.0.2.5/lib/mono
```

So at this point, /usr/local/lib/mono just points to the mono cellar's lib directory, as intended. This is crucial because under the mono/lib directory hierarchy we have the directory which will eventually be referred to by the ProjectScaffold fsproj files: `$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets`

The obvious question above is "where do the two variables point to", so I ask xbuild:

```
dcohenp@eizbook:~$  xbuild /v:diag | grep MSBuildExtensionsPath
MSBuildExtensionsPath = /usr/local/Cellar/mono/4.0.2.5/lib/mono/xbuild
MSBuildExtensionsPath32 = /usr/local/Cellar/mono/4.0.2.5/lib/mono/xbuild
MSBuildExtensionsPath64 = /usr/local/Cellar/mono/4.0.2.5/lib/mono/xbuild
````

On the other had, `VisualStudioVersion` is undefined, so it will be replaced by an empty string, so the final location it expects for this file is **`/usr/local/Cellar/mono/4.0.2.5/lib/mono/xbuild/Microsoft/VisualStudio/v/FSharp/Microsoft.FSharp.Targets`**. Of course, that file doesn't exist yet since I haven't installed fsharp, but at least the containing directory should be there:

```
dcohenp@eizbook:~$ ls -l /usr/local/Cellar/mono/4.0.2.5/lib/mono/xbuild/Microsoft/VisualStudio/
total 0
drwxr-xr-x  3 dcohenp  admin  102 Jul 11 00:52 v10.0/
drwxr-xr-x  3 dcohenp  admin  102 Jul 11 00:52 v11.0/
drwxr-xr-x  3 dcohenp  admin  102 Jul 11 00:52 v9.0/
```

Note here something that I had missed in my previous comment: xbuild seems to be canonicalizing the path, so although it probably _started off_ with `/usr/local/lib/mono/xbuild`, during runtime **it will actually look at ```<CELLAR>/lib/mono/xbuild```**.

The point where this becomes relevant is when you install fsharp. What I would expect from this package is a couple of things: the entire hierarchy of files and settings, and **the `v`symlink in the above directory that makes it findable by the ´fsproj´ files**.

```
dcohenp@eizbook:~$ brew install fsharp
==> Downloading https://homebrew.bintray.com/bottles/fsharp-3.1.2.4.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/fsharp-3.1.2.4.yosemite.bottle.tar.gz
==> Pouring fsharp-3.1.2.4.yosemite.bottle.tar.gz
==> Caveats
To run programs built with fsharpc you need to set:
  export MONO_GAC_PREFIX="/usr/local"
==> Summary
🍺  /usr/local/Cellar/fsharp/3.1.2.4: 56 files, 21M
dcohenp@eizbook:~$ ls -ld /usr/local/lib/mono
drwxr-xr-x  14 dcohenp  admin  476 Jul 27 03:12 /usr/local/lib/mono/
```

And here is where it all starts going haywire. As you can see, the `mono` symlink above has been replaced by an actual concrete directory, with the contents that the fsharp keg meant to merge with the existing mono directory hierarchy. So we sadly now have two parallel hierarchies:

```
dcohenp@eizbook:~$ ls -l /usr/local/Cellar/mono/4.0.2.5/lib/mono/xbuild/Microsoft/VisualStudio/
total 0
drwxr-xr-x  3 dcohenp  admin  102 Jul 11 00:52 v10.0/
drwxr-xr-x  3 dcohenp  admin  102 Jul 11 00:52 v11.0/
drwxr-xr-x  3 dcohenp  admin  102 Jul 11 00:52 v9.0/
dcohenp@eizbook:~$ ls -l /usr/local/lib/mono/xbuild/Microsoft/VisualStudio/
total 16
lrwxr-xr-x  1 dcohenp  admin   77 Jul 27 03:12 v@ -> ../../../../../Cellar/fsharp/3.1.2.4/lib/mono/xbuild/Microsoft/VisualStudio/v
drwxr-xr-x  3 dcohenp  admin  102 Jul 27 03:12 v10.0/
drwxr-xr-x  3 dcohenp  admin  102 Jul 27 03:12 v11.0/
lrwxr-xr-x  1 dcohenp  admin   81 Jul 27 03:12 v12.0@ -> ../../../../../Cellar/fsharp/3.1.2.4/lib/mono/xbuild/Microsoft/VisualStudio/v12.0
drwxr-xr-x  3 dcohenp  admin  102 Jul 27 03:12 v9.0/
```

And given what we saw above, since xbuild is canonicalizing its paths, it will look into the first directory but not the second. Ergo, failure.

I tried scratching the surface of the Homebrew package and it _seems_ to me like by the time the `post_install` function is called, the directories are already screwed up, so I'm guessing the problem is probably related to how the tarball itself is packaged/unpackaged. I haven't had the time to try building from source but that would be an interesting experiment to attempt.

In the meantime, if anyone wants a workaround, just re-creating a second copy of the `v` symlink seems to get ProjectScaffold building just fine:

```
dcohenp@eizbook:/usr/local/Cellar/mono/4.0.2.5/lib/mono/xbuild/Microsoft/VisualStudio$ ln -s /usr/local/Cellar/fsharp/3.1.2.4/lib/mono/xbuild/Microsoft/VisualStudio/v .
```

**Comment by dsyme** [comment] 2015-07-27 10:12
OK, yes, well, at least we understand the issue now - homebrew F# certainly seems to mess up a homebrew install of mono.

There must be ways of making this work but it will need more work in the homebrew formula

**Comment by rneatherway** [comment] 2015-07-27 11:08
@dcohenp: Could you try rerunning the installation of fsharp with `--verbose --debug` so we can see what it is doing that overrides the `/usr/local/lib/mono` directory. I've looked at the mono and fsharp recipes and I can't see any difference that looks like it could be causing this behaviour.

Once we have this working we should definitely update the `test` section to use `xbuild` so that this bad installation doesn't occur silently anymore.

**Comment by dcohenp** [comment] 2015-07-28 03:35
OK, here's the output of, having previously deleted fsharp and mono, installing them both with `--verbose --debug`: https://gist.github.com/dcohenp/ce97ee99dcfea1cb6d95

My favorite part is [this](https://gist.github.com/dcohenp/ce97ee99dcfea1cb6d95#file-brew-fsharp-txt-L326):

```
==> Pouring fsharp-3.1.2.4.yosemite.bottle.tar.gz
tar xf /Library/Caches/Homebrew/fsharp-3.1.2.4.yosemite.bottle.tar.gz
==> Caveats
To run programs built with fsharpc you need to set:
  export MONO_GAC_PREFIX="/usr/local"
==> Finishing up
ln -s ../Cellar/fsharp/3.1.2.4/bin/fsharpc fsharpc
ln -s ../Cellar/fsharp/3.1.2.4/bin/fsharpi fsharpi
ln -s ../Cellar/fsharp/3.1.2.4/bin/fsharpiAnyCpu fsharpiAnyCpu
rm /usr/local/lib/mono  #### WTF?!
```

**Comment by sgtz** [comment] 2015-07-28 06:38
that'd remove would remove the symlink to the cellar folder in this case.  A little suspicious.  Where is this postinstall.rb file located?  Perhaps this is what needs to be patched?  Pity the /usr/local/lib area gets spammed with so many mono symlinks -- perhaps changing the path statement would be better. Beyond the scope of this bug fix though.

**Comment by rneatherway** [comment] 2015-07-28 16:21
Yes, more than suspicious I would say! I think that `postinstall.rb` file is mentioned at the bottom as `/usr/local/Library/Homebrew/postinstall.rb`, so it looks like a common Homebrew file.

This issue is still open: https://github.com/Homebrew/homebrew/issues/36286, I'll post there and see if anyone will comment.

**Comment by rneatherway** [comment] 2015-07-29 05:58
I think we've tracked the problem down. The loader bash script `xbuild` is pointing at the version of xbuild.exe under the private prefix (where there is no `.../VisualStudio/v/...` rather than the symlink under `/usr/local/bin`. So I think actually the mono recipe should be updated. See discussion at https://github.com/Homebrew/homebrew/issues/36286

**Comment by haf** [comment] 2015-10-23 14:59
This issue should be closed because it's been fixed by @rneatherway et al in Homebrew.

**Comment by rneatherway** [comment] 2015-10-23 15:31
Right, fixed by https://github.com/Homebrew/homebrew/issues/36286

**Closed by rneatherway** 2015-10-23 15:31 UTC
