### ISSUE TITLE
F# on .Net Core: 'Task<'disposable>' is not compatible with the type 'IDisposable'

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#605] opened 2016-08-26 18:14 UTC
```fsharp
 // This is a compile only test.
 let testSyntax (xT: Task<'disposable>)
                (xE: IEvent<int>)
                (xO: IObservable<float>)
                (t: Task)
                (xA: Async<int>)
                (xs: seq<float>)
                (uJ: Job<unit>) = job {
   let! _ = xE
   let! _ = xO
   let! _ = xT
   let! _ = xA
   do! t
   do! uJ
   if true then
     return ()
   use xT' = xT
```

Fails on the last line. The "normal" compiler infers that `xT'` is of type `IDisposable`.

See https://github.com/Hopac/Hopac/pull/118 specifically [this line](https://github.com/Hopac/Hopac/pull/118/files#diff-dc7fa8db6e7a7c5c82df48c459590103R35)

**Comment by enricosada** [comment] 2016-09-09 10:58
@haf can you close this one? is a dupe of Microsoft/visualfsharp#1503

as per [CONTRIBUTING.md](https://github.com/fsharp/fsharp/blob/master/CONTRIBUTING.md)

Is the issue a general bug in the F# compiler/core library? Use the Microsoft/visualfsharp repository

**Closed** 2016-09-12 17:14 UTC
