### ISSUE TITLE
Can't use generic parameter as constraint for other parameter

### ISSUE THREAD

**Issue by TheGrandUser** [fsharp/fsharp#634] opened 2016-10-31 21:52 UTC
I seem to be unable to constrain one generic type to another generic type, such as in

let doThing<'D, 'B when 'D :> 'B> () = ()

I would expect this to be equivalent to the C# version

void DoThing<D, B> where D : B { }

But the F# gives me several errors
on doThing "One or more of the explicit class or function type variables for this binding could not be generalized, because they were constrained to other types"
on 'D "This type parameter has been used in a way that constrains it to always be ''B'"
and on 'D :> 'B "Invalid constraint: the type used for the constraint is sealed, which means the constraint could only be satisfied by at most one solution"

Seems to me the root problem is that it's treating the generic 'B as sealed. Is there some way to explicitly not treat it like that? Is that intended behavior?

Using VS 2015

**Comment by dsyme** [comment] 2016-11-01 11:47
Duplicate of https://github.com/fsharp/fslang-suggestions/issues/255

**Closed by dsyme** 2016-11-01 11:47 UTC
