### ISSUE TITLE
Make out-of-tree builds work 

### ISSUE THREAD

**Issue by rtollert** [fsharp/fsharp#438] opened 2015-07-07 19:41 UTC
The default value of --with-bootstrap is the relative path 'lib/bootstrap', which is converted to an absolute path via $(cd $path && pwd), cf https://github.com/fsharp/fsharp/blob/5ad346768d0f6c82594ca4ea6143f7743a209299/configure.ac#L44 .

If the build directory is different than the source distribution, so that, e.g., configure is called as '../fsharp/configure', this will fail, because lib/bootstrap doesn't exist in the build directory.

**Comment by knocte** [comment] 2015-07-07 19:49
Yeah, this repository is unfortunately not compatible yet with out-of-tree builds. Patches welcome.

**Comment by dsyme** [comment] 2017-03-30 17:28
I'm closing this because the issue is so old.  Please just submit a PR to make this work if you need it

**Closed by dsyme** 2017-03-30 17:28 UTC
Labels: Suggestion
