### ISSUE TITLE
Yield prevents implicit cast to interface type

### ISSUE THREAD

**Issue by FrankBro** [fsharp/fsharp#545] opened 2016-02-14 22:14 UTC
Using yield when building a collection seems to prevent implicit cast to the interface type expected

```fsharp
type IFirst = interface end

type ISecond = 
    inherit IFirst

module Test = 
    let instance = { new ISecond }

    let test () =
        let a : IFirst list =
            [
                instance
            ]
        let b : IFirst list = 
            [
                yield instance
            ]
        ()
```

In this example, you will get an error for `b`:

```
This expression was expected to have type
    IFirst    
but here has type
    ISecond
```

**Comment by dsyme** [comment] 2016-04-08 22:07
Right now this is by design.  Since this is a language change suggestion, please add it to http://fslang.uservoice.com.

**Comment by dsyme** [comment] 2016-04-08 22:11
Closing as this should go in user voice as mentioned above please.  Thanks!

**Closed by dsyme** 2016-04-08 22:11 UTC

**Comment by smoothdeveloper** [comment] 2016-04-10 10:03
https://fslang.uservoice.com/forums/245727-f-language/suggestions/13361034-implement-implicit-casts-for-yield
