### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by tathanhdinh** [fsharp/fsharp#621] opened 2016-10-09 23:26 UTC
#### Repro steps

1. Create a default Fsharp project with mono-develop

2. Build this project

#### Expected behavior

Build should be success without any warning nor error.

#### Actual behavior

`/usr/lib/mono/fsharp/Microsoft.FSharp.Targets: error : Error executing task Fsc: Object reference not set to an instance of an object`

#### Related information 

* This bug happens with `master` version. 
* The version `4.0.1.10` can compile this project without any error.

**Comment by knocte** [comment] 2016-10-10 09:23
What version of monodevelop please?
Also, it seems this bug should be submitted in http://bugzilla.xamarin.com/, not here.

**Comment by tathanhdinh** [comment] 2016-10-10 20:37
I am not sure whether it is a bug of `MonoDevelop` or not. Someone has a similar issue [here](https://bugzilla.xamarin.com/show_bug.cgi?id=44801). I found also that the file `Microsoft.FSharp.Targets` and the corresponding dll of the task `Fsc` are generated when building and installing `fsharp`.

**Comment by knocte** [comment] 2016-10-11 02:08
> I am not sure whether it is a bug

To figure that out, we need to reproduce your exact problem. And to do that, we need more information from you. You still haven't told us what operating system are you using, what version of it, and what version of monodevelop (and how did you install it).

**Comment by dsyme** [comment] 2016-10-11 22:39
Closing as this seems to be external

**Closed by dsyme** 2016-10-11 22:39 UTC

**Comment by tathanhdinh** [comment] 2016-10-14 12:46
@knocte and @dsyme : Sorry for this retard but I think this is not an external bug (i.e. coming from MonoDevelop) since I can compile successfully the same projects with `fsharp-4.0.1.10`, whereas the `master` and `4.0.1.13`. 

I am using now MonoDevelop version `5.10` and Fedora 24 (kernel `4.7.6-200.fc24.x86_64`).

**Comment by knocte** [comment] 2016-10-15 04:45
Check if you can reproduce the issue with MonoDevelop 6.1 please.

**Comment by dsyme** [comment] 2016-10-18 00:31
@tathanhdinh Thanks the update

**Comment by samritchie** [comment] 2016-10-19 13:39
This looks similar to the failing [homebrew PR](https://github.com/Homebrew/homebrew-core/pull/5990) ([log output](https://bot.brew.sh/job/Homebrew%20Core/9575/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_mono/)). Is there an incompatibility between mono 4.6.1.5 and fsharp > 4.0.1.10?

**Comment by dsyme** [comment] 2016-10-19 16:03
@samritchie Not aware of any specific problems besides the logs linked here

CI is passing OK for 4.6.1.5, e.g. see the history here: https://travis-ci.org/fsharp/fsharp/


Mono JIT compiler version 4.6.1 (Stable 4.6.1.5/ef43c15 Wed Oct 12 09:10:37 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com

**Comment by samritchie** [comment] 2016-10-20 00:35
Thanks @dsyme, as far as I can tell, this was a homebrew sandboxing problem (https://github.com/Homebrew/homebrew-core/issues/5302). A PR for the latest mono/fsharp has been merged now.

**Comment by samritchie** [comment] 2016-10-20 08:06
Hmm, after I updated via mono I also started getting the error. It looks like it’s triggered when you have an fsproj with no `<DefineConstants>` set, meaning it will break on some templates & existing projects. 

I’m unsure whether this is the correct behaviour or not?

**Comment by samritchie** [comment] 2016-10-20 13:15
Ah, nm - I’ve just seen #628

**Comment by tathanhdinh** [comment] 2016-10-22 00:30
@samritchie @dsyme : many thanks, I believe that [#628](https://github.com/fsharp/fsharp/issues/628) is also the problem reported here.

**Comment by dsyme** [comment] 2016-10-24 15:31
@tathanhdinh Great
