### ISSUE TITLE
F# type constructor doesn't act like a function

### ISSUE THREAD

**Issue by brianberns** [fsharp/fsharp#660] opened 2017-02-02 04:09 UTC
If I define a type like this:

`type Foo = Items of seq<int>`

I can create a `Foo` as follows:

`Items [1;2;3]`

However, the following doesn't work:

`[1;2;3] |> Items`

The error message is:

```
Type mismatch. Expecting a
    int list -> 'a    
but given a
    seq<int> -> Foo
```

Shouldn't the compiler be able to convert an `int list` into a `seq<int>`? If the `Items` constructor was a normal function, I could invoke it either way:

```
let length ints = Seq.length ints
printfn "%A" (length [1;2;3])
printfn "%A" ([1;2;3] |> length)
```

Environment: F# 4 in Visual Studio 2015 on Windows 7

See http://stackoverflow.com/questions/41989566/f-type-constructor-doesnt-act-like-a-function

**Comment by nikonthethird** [comment] 2017-02-02 15:26
I want to point out that if you declare the constructor as another function, it works:

```fsharp
type Foo = Items of seq<int>
let items = Items
[1;2;3] |> items // works
[1;2;3] |> Items // does not work
```

**Comment by enricosada** [comment] 2017-02-10 11:17
@brianberns @nikonthethird as per [CONTRIBUTING.md](https://github.com/fsharp/fsharp/blob/master/CONTRIBUTING.md)

The issue is a general bug in the F# compiler/core library, so should be opened in the [Microsoft/visualfsharp](https://github.com/microsoft/visualfsharp/) repository. That should help track better your issue.

This repo is for packaging only.

**Comment by dsyme** [comment] 2017-02-20 12:12
Closing this as it is in visualfsharp

**Closed by dsyme** 2017-02-20 12:12 UTC
