### ISSUE TITLE
struct problem in F# interactive

### ISSUE THREAD

**Issue by lust4life** [fsharp/fsharp#799] opened 2017-11-18 05:38 UTC
Please provide a succinct description of the issue.

#### Repro steps

1.  Run the following code in F# interactive :
```fsharp
[<Struct>]
type Foo (pos : int) =
  member x.Pos = pos
  member x.IsPos with get() = x.Pos >= 0

let foo = Foo (-1)  
foo
foo.IsPos
```

output:
```shell
Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> # silentCd @"/home/lust/git/temp";;
- # 1 @"/home/lust/git/temp/test.fsx"
- ;;
> [<Struct>]
- type Foo (pos : int) =
-   member x.Pos = pos
-   member x.IsPos with get() = x.Pos >= 0
-
- let foo = Foo (-1)
- ;;
type Foo =
  struct
    new : pos:int -> Foo
    member IsPos : bool
    member Pos : int
  end
val foo : Foo = FSI_0002+Foo

> foo
- ;;
val it : Foo = FSI_0002+Foo {IsPos = false;
                             Pos = -1;}

> foo.IsPos
- ;;
val it : bool = true
```

#### Expected behavior

```shell
> foo.IsPos
- ;;
val it : bool = false
```

#### Actual behavior
```shell
> foo.IsPos
- ;;
val it : bool = true
```

#### Known workarounds

remove `<Struct>` will not have the problem.

#### Related information 

Provide any related information 

* Ubuntu 16.04.3 LTS
* Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 20:37:08 UTC 2017)
* vscode

**Comment by dsyme** [comment] 2017-11-18 15:03
Well that would be odd.   I'm not seeing this problem on Windows.  Can anyone confirm on Ubuntu?

**Comment by dsyme** [comment] 2017-11-18 15:06
On Windows:
```
C:\GitHub\dsyme\visualfsharp>fsi

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> [<Struct>]
- type Foo (pos : int) =
-   member x.Pos = pos
-   member x.IsPos with get() = x.Pos >= 0
-
- ;;
type Foo =
  struct
    new : pos:int -> Foo
    member IsPos : bool
    member Pos : int
  end

> let foo = Foo (-1)
- ;;
val foo : Foo = FSI_0002+Foo

> foo;;
val it : Foo = FSI_0002+Foo {IsPos = false;
                             Pos = -1;}

> foo.IsPos;;
val it : bool = false

> #q;;
```

**Comment by knocte** [comment] 2017-11-19 06:48
Cannot reproduce with Ubuntu 16.04.x, Mono 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Comment by knocte** [comment] 2017-11-19 07:01
Bug confirmed for me in Ubuntu 17.10 with Mono 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017) <-- installed from Mono repositories

**Comment by knocte** [comment] 2017-11-19 07:06
Cannot reproduce either on Ubuntu 17.10 with Mono 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1) <-- instaled from Ubuntu repos.

Therefore, seems to be a regression in Mono that happened somewhere between 4.6.2 and 5.4.0.201.

**Comment by dsyme** [comment] 2017-11-19 07:20
Can someone open a bug on Mono bugzilla please? Paste the link here too.

**Comment by nosami** [comment] 2017-11-19 11:46
Working on OSX / Mono 5.8


```
13:34 $ fsharpi

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> [<Struct>]
- type Foo (pos : int) =
-   member x.Pos = pos
-   member x.IsPos with get() = x.Pos >= 0;;
type Foo =
  struct
    new : pos:int -> Foo
    member IsPos : bool
    member Pos : int
  end

> let foo = Foo (-1)
- ;;
val foo : Foo = FSI_0002+Foo

> foo;;
val it : Foo = FSI_0002+Foo {IsPos = false;
                             Pos = -1;}

> foo.IsPos;;
val it : bool = false
```

**Comment by dsyme** [comment] 2017-11-21 16:17
@nosami Thanks for checking!  I think we just close this as a Mono glitch

**Closed by dsyme** 2017-11-21 16:17 UTC
Labels: bug (divergence)

**Comment by lust4life** [comment] 2017-11-21 19:59
thanks for checking.
