### ISSUE TITLE
F# interactive reflection null error

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#488] opened 2015-09-01 20:10 UTC
In the same code as in the previous issue, no #487 , in this code: https://github.com/haf/EventStore.Client.FSharp/blob/master/src/EventStore.ClientAPI.FSharp/EventStore.Client.FSharp.fs#L128

I have this interactive session:

```

> System.Runtime.Serialization.FormatterServices.GetUninitializedObject(typeof<EventStore.ClientAPI.RecordedEvent>);;

val it : obj = EventStore.ClientAPI.RecordedEvent

> typeof<RecordedEvent>.FullName;;

val it : string = "EventStore.ClientAPI.RecordedEvent"

> let emptyCtor = fun () -> System.Runtime.Serialization.FormatterServices.GetUninitializedObject(typeof<'a>) :?> 'a;;
val emptyCtor : unit -> 'a

> let (x : RecordedEvent) = emptyCtor ();;

val x : RecordedEvent

> x;;

val it : RecordedEvent = EventStore.ClientAPI.RecordedEvent

> (taken from the linked line of code)
val reflPkgFor : unit -> (unit -> 'a) * (string -> obj -> 'a -> 'a)

> let (ctor, setter) = reflPkgFor<RecordedEvent>();;

Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.InvalidCastException: Cannot cast from source type to destination type.
  at (wrapper castclass) object:__castclass_with_cache (object,intptr,intptr)
  at Microsoft.FSharp.Compiler.Interactive.Shell+Utilities+AnyToLayoutSpecialization`1[Microsoft.FSharp.Core.FSharpFunc`2[System.String,Microsoft.FSharp.Core.FSharpFunc`2[System.Object,Microsoft.FSharp.Core.FSharpFunc`2[EventStore.ClientAPI.RecordedEvent,EventStore.ClientAPI.RecordedEvent]]]].Microsoft-FSharp-Compiler-Interactive-Shell-Utilities-IAnyToLayoutCall-FsiAnyToLayout (Internal.Utilities.StructuredFormat.FormatOptions options, System.Object o) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Compiler.Interactive.Shell+FsiValuePrinter.PrintValue (Microsoft.FSharp.Compiler.Interactive.FsiValuePrinterMode printMode, Internal.Utilities.StructuredFormat.FormatOptions opts, System.Object x, System.Type ty) [0x00000] in <filename unknown>:0 
Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.InvalidCastException: Cannot cast from source type to destination type.
  at (wrapper castclass) object:__castclass_with_cache (object,intptr,intptr)
  at Microsoft.FSharp.Compiler.Interactive.Shell+Utilities+AnyToLayoutSpecialization`1[Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharp.Core.Unit,EventStore.ClientAPI.RecordedEvent]].Microsoft-FSharp-Compiler-Interactive-Shell-Utilities-IAnyToLayoutCall-FsiAnyToLayout (Internal.Utilities.StructuredFormat.FormatOptions options, System.Object o) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Compiler.Interactive.Shell+FsiValuePrinter.PrintValue (Microsoft.FSharp.Compiler.Interactive.FsiValuePrinterMode printMode, Internal.Utilities.StructuredFormat.FormatOptions opts, System.Object x, System.Type ty) [0x00000] in <filename unknown>:0 
val setter : (string -> obj -> RecordedEvent -> RecordedEvent) = 
val ctor : (unit -> RecordedEvent) = 

> ctor();;

val it : RecordedEvent = null

> 
val emptyCtor : unit -> 'a

> 
```

So as you can see, when I invoke `emptyCtor`, I get the uninitialised object instance, but when I do it with the `emptyCtor` inside the other, I get null back.

(The reason I have to do this is because EventStore likes to have private constructors (perhaps I should just invoke those instead, but that's a lot more time to sink into an already expensive F# lib).)

Expected outcome: equational equality; invoking a function outside of another should not give different results.

**Comment by dsyme** [comment] 2015-09-03 11:53
Is it possible to simplify the repro for this please? Just down to a single piece of code.  And is this on Linux with Mono or Windows with .NET?

**Comment by rschmitt** [comment] 2015-10-09 01:56
Which version of F# did you run this session on? I can't reproduce this on OS X using the latest HEAD build of fsharp.

**Comment by haf** [comment] 2015-10-09 09:52
It may be problems with FSharp.Core nuget...

**Comment by dsyme** [comment] 2015-12-01 11:18
I'm closing this for now - there was a recent fix in Microsoft\visualfsharp to catch an unexpected null case in printing.

**Closed by dsyme** 2015-12-01 11:18 UTC
Labels: discussion
