### ISSUE TITLE
Error building fsharp when using Mono built from source only

### ISSUE THREAD

**Issue by caxelrud** [fsharp/fsharp#387] opened 2015-02-21 18:21 UTC
Mono is installed at /mono . It was build from source,
I did the following commands:
> $ cd fsharp-master
> $ export PKG_CONFIG_PATH=/mono/lib/pkgconf
> $ export PATH=$PATH:/mono/bin
> $ echo $PATH
>   /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/mono/bin
> $ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/mono/lib/
> $echo $LD_LIBRARY_PATH
    :/mono/lib/
>$ ./autogen.sh --prefix /mono

I go the following:
>checking whether make sets $(MAKE)... yes
checking for pkg-config... /usr/bin/pkg-config
configure: "pkg-config: /usr/bin/pkg-config"
configure: "PKG_CONFIG_LIBDIR: "
configure: PCL Reference Assemblies for Profile 47 found: no
configure: PCL Reference Assemblies for Profile 7 found: no
configure: PCL Reference Assemblies for Profile 78 found: no
configure: PCL Reference Assemblies for Profile 259 found: no
configure: creating ./config.status
config.status: creating launcher
config.status: creating Makefile
config.status: creating config.make
config.status: creating src/fsharp/Makefile
config.status: creating src/fsharp/FSharp.Build-proto/Makefile
config.status: creating src/fsharp/FSharp.Compiler-proto/Makefile
config.status: creating src/fsharp/Fsc-proto/Makefile
config.status: creating src/fsharp/FSharp.Core/Makefile
config.status: creating src/fsharp/FSharp.Build/Makefile
config.status: creating src/fsharp/FSharp.Compiler/Makefile
config.status: creating src/fsharp/Fsc/Makefile
config.status: creating src/fsharp/FSharp.Compiler.Interactive.Settings/Makefile
config.status: creating src/fsharp/FSharp.Compiler.Server.Shared/Makefile
config.status: creating src/fsharp/FSharp.Data.TypeProviders/Makefile
config.status: creating src/fsharp/fsi/Makefile
config.status: creating src/fsharp/fsiAnyCpu/Makefile
config.status: creating src/fsharp/policy.2.0.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.2.3.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.3.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.4.0.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.4.3.FSharp.Core/Makefile

And the following command:
>$ make

I got the following error:
>make -C src/fsharp all
make[1]: Entering directory '/home/monoc/fsharp-master/src/fsharp'
make build-proto
make[2]: Entering directory '/home/monoc/fsharp-master/src/fsharp'
mkdir: can't create directory '/home/monoc/fsharp-master//lib/proto/': File exists
Makefile:15: recipe for target 'build-proto' failed
make[2]: [build-proto] Error 1 (ignored)
cp -p /home/monoc/fsharp-master/lib/bootstrap/4.0/FSharp.Core.dll /home/monoc/fsharp-master//lib/proto/FSharp.Core.dll
cp -p /home/monoc/fsharp-master/lib/bootstrap/4.0/FSharp.Core.sigdata /home/monoc/fsharp-master//lib/proto/FSharp.Core.sigdata
cp -p /home/monoc/fsharp-master/lib/bootstrap/4.0/FSharp.Core.optdata /home/monoc/fsharp-master//lib/proto/FSharp.Core.optdata
make -C FSharp.Build-proto Configuration=proto build-proto
make[3]: Entering directory '/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto'
MONO_ENV_OPTIONS= xbuild /p:Configuration=Proto
XBuild Engine Version 12.0
Mono, Version 3.12.0.0
Copyright (C) 2005-2013 Various Mono authors
Build started 02/21/2015 17:57:35.
__________________________________________________
Project "/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj" (default target(s)):
        Target CallFsSrGen:
                Tool /home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/fssrgen.exe execution started with arguments:  /home/monoc/fsharp-master/src/fsharp/FSharp.Build/FSBuild.txt  obj/proto/./FSBuild.fs  FSBuild.resx
/home/monoc/fsharp-master/lib/bootstrap/4.0/FSharp.SRGen.targets: error : Error executing tool '/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/fssrgen.exe': ApplicationName='/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/fssrgen.exe', CommandLine=' /home/monoc/fsharp-master/src/fsharp/FSharp.Build/FSBuild.txt  obj/proto/./FSBuild.fs  FSBuild.resx ', CurrentDirectory='/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto', Native error= Cannot find the specified file
        Task "FsSrGen" execution -- FAILED
        Done building target "CallFsSrGen" in project "/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj".-- FAILED
Done building project "/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj".-- FAILED
Build FAILED.
Errors:
/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj (default targets) ->
/home/monoc/fsharp-master/lib/bootstrap/4.0/FSharp.SRGen.targets (CallFsSrGen target) ->
        /home/monoc/fsharp-master/lib/bootstrap/4.0/FSharp.SRGen.targets: error : Error executing tool '/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/fssrgen.exe': ApplicationName='/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/fssrgen.exe', CommandLine=' /home/monoc/fsharp-master/src/fsharp/FSharp.Build/FSBuild.txt  obj/proto/./FSBuild.fs  FSBuild.resx ', CurrentDirectory='/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto', Native error= Cannot find the specified file
         0 Warning(s)
         1 Error(s)
Time Elapsed 00:00:02.2930690
Makefile:9: recipe for target 'build-proto' failed
make[3]: *** [build-proto] Error 1
make[3]: Leaving directory '/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto'
Makefile:15: recipe for target 'build-proto' failed
make[2]: *** [build-proto] Error 2
make[2]: Leaving directory '/home/monoc/fsharp-master/src/fsharp'
Makefile:10: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/monoc/fsharp-master/src/fsharp'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dsyme** [comment] 2015-03-21 13:30
FWIW the error line is below. I don't know what's causing this - Mono should be able to execute this binary.    We don't CI a complete fresh build of Mono + F#.  Did you install any Mono package, or are you really building absolutely everything from scratch?

There's a chance it's related to FsSrGen.exe being a .NET 2.0 binary, though I hope not (I'd find it odd if a fresh compile of Mono didn't run a .NET 2.0 binary).



```
/home/monoc/fsharp-master/lib/bootstrap/4.0/FSharp.SRGen.targets: error : Error executing tool '/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/fssrgen.exe': ApplicationName='/home/monoc/fsharp-master/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/fssrgen.exe', CommandLine=' /home/monoc/fsharp-master/src/fsharp/FSharp.Build/FSBuild.txt obj/proto/./FSBuild.fs FSBuild.resx ', 
```

**Comment by caxelrud** [comment] 2015-03-28 17:44
For Mono, I built it everything from scratch to be able to run it in Intel Edison.
I followed the procedure described at http://www.dlsloan.ca/Docs/Edison/monoInstall.html .
It works well for few test with C#.

**Comment by haf** [comment] 2015-04-25 21:39
Pure speculation: is it because mono v4.0 is dropping .Net 2.0 support, perhaps? "We dropped support for the 2.0, 3.5 and 4.0 assemblies" from http://www.mono-project.com/docs/about-mono/releases/4.0.0/

**Comment by dsyme** [comment] 2015-06-24 05:50
@haf - What are the ramifications of this for the F# build?  Do you think it's the cause of the problem above? thanks

**Comment by haf** [comment] 2015-06-24 07:24
Shouldn't. Checked on chat; .Net 2.0 usage should still be transparent to the user.

**Comment by dsyme** [comment] 2015-07-07 18:12
Is this bug still a problem?  I think this may have been a Mono bug that has been fixed?

**Comment by dsyme** [comment] 2015-07-07 18:15
Closing as I believe this is a Mono bug that's been fixed. Please let us know exact repro steps if otherwise.

**Closed by dsyme** 2015-07-07 18:15 UTC
