### ISSUE TITLE
Type Alias/Abbreviation working correctly (generics)?

### ISSUE THREAD

**Issue by gentauro** [fsharp/fsharp#717] opened 2017-04-12 11:47 UTC
**Please provide a succinct description of the issue.**

I have created the following generic `Type Alias/Abbreviation` to add the `Foo` alias to a generic type.

I have also added a `foo` function that can be called with an argument of a generic type that will be marked with the defined type `Foo` (it's like the identity function, but changes the values type signature). See `foo` and `bar`. This works perfectly.

Finally, I have added a function that takes the generic `Foo` value and removes the `Type Alias/Abbreviation`. Just think of it as the reverse of `foo`. See `baz` and `qux`. This doesn't seem to work.

```fsharp
type 'a Foo = 'a

let foo (x:'a) : 'a Foo = x
let bar = foo 042 (* int Foo *)
let baz (x:'a Foo) : 'a = x
let qux = baz bar (* int Foo but expected int *)

(*
> type 'a Foo = 'a
> val foo : x:'a -> 'a Foo
> val bar : int Foo = 42
> val baz : x:'a Foo -> 'a
> val qux : int Foo = 42
*)
```

#### Repro steps

**Provide the steps required to reproduce the problem**

1. Just create a generic `Type Alias/Abbreviation` like: `type 'a Foo = 'a`

2. Define a function that takes a value of the type described in previous step and returning the generic type value (without `Foo`) like: `let baz (x:'a Foo) : 'a = x`

3. Call the function

#### Expected behavior

**Provide a description of the expected behaviour.**

The expected type signature should be of the value `'a`

#### Actual behavior

**Provide a description of the actual behaviour observed.** 

But it isn't, the type signature is still of the type `'a Foo` even though the return value is specified on the function.

#### Known workarounds

**Provide a description of any known workarounds.**

I found this comment on SO:

```fsharp
(* StackOverflow.com -> http://stackoverflow.com/a/501116 *)
#nowarn "42"
let inline retype (x:'a Foo) : 'b = (# "" x : 'b #)

let meh01 : int   = retype bar
let meh02 : float = retype bar
let meh03 () = retype bar

(*
> val inline retype : x:'a Foo -> 'b
> val meh01 : int = 42
> val meh02 : float = 0.0
> val meh03 : unit -> 'a
*)
```

But really don't seem to fix the issue, rather that, it seems to introduce some bad behaviour ...

#### Related information 

Provide any related information 

* Operating system: **Ubuntu 16.04.1 LTS**
* Branch
* .NET Runtime, CoreCLR or Mono Version: **Mono JIT compiler version 4.2.1** and **F# Interactive for F# 4.0**
* Editing Tools (e.g. Visual Studio Version): **Emacs**
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions: **None**
* Links to performance testing scripts: **None**
* Indications of severity: Low

**Comment by dsyme** [comment] 2017-04-12 23:37
@gentauro This would go to Microsoft/visualfsharp

But TBH we would close this as "by design" - the types ``'a`` and ``'a Foo`` are equivalent, and we don't guarantee which will be shown to the user

**Closed by dsyme** 2017-04-12 23:37 UTC
